"""Pandas executor.

Runs a validated list of WorkflowStep against a DataFrame in order.
Returns an ExecutionResult with a preview, column list, and per-step logs.
"""
import io
import logging
import math

import pandas as pd

from app.core.exceptions import ExecutionError
from app.models.workflow import (
    ExecutionResult,
    FilterRowsStep,
    GenerateSummaryStep,
    GroupByStep,
    RemoveMissingValuesStep,
    RenameColumnsStep,
    SelectColumnsStep,
    SortValuesStep,
    StepLog,
    WorkflowStep,
)

logger = logging.getLogger(__name__)

_PREVIEW_ROWS = 5
_FILTER_OPS = {
    "=": lambda s, v: s == v,
    "!=": lambda s, v: s != v,
    ">": lambda s, v: s > v,
    ">=": lambda s, v: s >= v,
    "<": lambda s, v: s < v,
    "<=": lambda s, v: s <= v,
}


def execute(steps: list[WorkflowStep], content: bytes) -> ExecutionResult:
    """Execute all steps sequentially and return the result."""
    try:
        df = pd.read_csv(io.BytesIO(content))
    except Exception as exc:
        raise ExecutionError(f"Failed to load dataset: {exc}") from exc

    logs: list[StepLog] = []
    has_summary = False

    for idx, step in enumerate(steps):
        rows_before = len(df)
        df, message = _apply_step(step, df, idx)
        logs.append(
            StepLog(
                step_index=idx,
                step_type=step.type,
                rows_before=rows_before,
                rows_after=len(df),
                message=message,
            )
        )
        if isinstance(step, GenerateSummaryStep):
            has_summary = True

    preview = _to_preview(df)
    logger.info("Execution complete: %d rows, %d columns", len(df), len(df.columns))

    return ExecutionResult(
        row_count=len(df),
        column_count=len(df.columns),
        columns=list(df.columns),
        preview=preview,
        logs=logs,
        has_summary=has_summary,
    )


# ---------------------------------------------------------------------------
# Step handlers
# ---------------------------------------------------------------------------

def _apply_step(
    step: WorkflowStep, df: pd.DataFrame, idx: int
) -> tuple[pd.DataFrame, str]:
    try:
        if isinstance(step, RemoveMissingValuesStep):
            return _remove_missing(df)
        if isinstance(step, SelectColumnsStep):
            return _select_columns(step, df)
        if isinstance(step, FilterRowsStep):
            return _filter_rows(step, df)
        if isinstance(step, GroupByStep):
            return _group_by(step, df)
        if isinstance(step, SortValuesStep):
            return _sort_values(step, df)
        if isinstance(step, RenameColumnsStep):
            return _rename_columns(step, df)
        if isinstance(step, GenerateSummaryStep):
            return df, "Summary requested — will be generated by the explainer."
    except ExecutionError:
        raise
    except Exception as exc:
        raise ExecutionError(f"Step {idx} ({step.type}) failed: {exc}") from exc

    raise ExecutionError(f"Step {idx}: unknown step type '{step.type}'.")


def _remove_missing(df: pd.DataFrame) -> tuple[pd.DataFrame, str]:
    before = len(df)
    result = df.dropna()
    removed = before - len(result)
    return result.reset_index(drop=True), f"Removed {removed} rows with missing values."


def _select_columns(
    step: SelectColumnsStep, df: pd.DataFrame
) -> tuple[pd.DataFrame, str]:
    missing = [c for c in step.columns if c not in df.columns]
    if missing:
        raise ExecutionError(f"select_columns: columns not found: {missing}")
    return df[step.columns].copy(), f"Selected columns: {step.columns}."


def _filter_rows(
    step: FilterRowsStep, df: pd.DataFrame
) -> tuple[pd.DataFrame, str]:
    if step.column not in df.columns:
        raise ExecutionError(f"filter_rows: column '{step.column}' not found.")
    op_fn = _FILTER_OPS[step.operator]
    mask = op_fn(df[step.column], step.value)
    result = df[mask].reset_index(drop=True)
    return result, (
        f"Filtered '{step.column}' {step.operator} {step.value!r}: "
        f"{len(result)} rows kept."
    )


def _group_by(
    step: GroupByStep, df: pd.DataFrame
) -> tuple[pd.DataFrame, str]:
    for col in (step.column, step.target):
        if col not in df.columns:
            raise ExecutionError(f"group_by: column '{col}' not found.")
    result = (
        df.groupby(step.column, as_index=False)[step.target]
        .agg(step.agg)
        .reset_index(drop=True)
    )
    return result, (
        f"Grouped by '{step.column}', aggregated '{step.target}' with {step.agg}."
    )


def _sort_values(
    step: SortValuesStep, df: pd.DataFrame
) -> tuple[pd.DataFrame, str]:
    if step.column not in df.columns:
        raise ExecutionError(f"sort_values: column '{step.column}' not found.")
    result = df.sort_values(by=step.column, ascending=step.ascending).reset_index(drop=True)
    direction = "ascending" if step.ascending else "descending"
    return result, f"Sorted by '{step.column}' {direction}."


def _rename_columns(
    step: RenameColumnsStep, df: pd.DataFrame
) -> tuple[pd.DataFrame, str]:
    missing = [c for c in step.mapping if c not in df.columns]
    if missing:
        raise ExecutionError(f"rename_columns: columns not found: {missing}")
    result = df.rename(columns=step.mapping)
    return result, f"Renamed columns: {step.mapping}."


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_preview(df: pd.DataFrame) -> list[dict]:
    raw = df.head(_PREVIEW_ROWS).to_dict(orient="records")
    return [
        {k: (None if isinstance(v, float) and math.isnan(v) else v) for k, v in row.items()}
        for row in raw
    ]
